import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from "react";
import { TRPCReactProvider } from "@/trpc/client";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


/**
 * Application root layout that applies global fonts, document language, and wraps page content with the TRPC provider.
 *
 * @param children - Content to render inside the application's body; will be wrapped by the TRPCReactProvider.
 * @returns The root HTML element containing the application body and its children.
 */
export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {

    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
              <TRPCReactProvider>
                  {children}
              </TRPCReactProvider>
             
            </body>
        </html>
    );
}
